### PR TITLE
Skip applying Still Needs Manual Backport label in backport PR

### LINKED ISSUE #93: Feature Request: Do not apply Still Needs Manual Backport label to backport PR
Workflow to trigger this:

1. Have two different backport labels applied, so when merged, a PR would be backported to two different release branches.
2. One of the release branch will have a failed backport, triggering the bot to apply "Still Needs Manual Backport".

Current behavior: If the failed backport happened first, the original PR will have "Still Needs Manual Backport" label applied. And then the backport to the other branch that succeeds after will also inherit this label.

Desired behavior: Bot is smart enough to not let the second backport to inherit this label.

Maybe not everyone will agree on this request, therefore I am opening an issue instead of attempting to patch it.

Example: https://github.com/astropy/astropy/pull/14104

### PR DESCRIPTION
**Pull request by pllim**
Fix #93 

Please double check to make sure I patched the correct place. Also not sure how to test this.

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
LGTM, thanks!

**Comment by blink1073** [comment]
Deployed!

**Comment by pllim** [comment]
Thanks! 🤞

**Comment by pllim** [comment]
Doesn't seem to work... https://github.com/astropy/astropy/pull/14107 :(

**Pull request merged**
