### PR TITLE
Add pre-commit command

### PR DESCRIPTION
**Pull request by blink1073**
- [x] Refactor `blackify` into utility functions for prepping the repo and pushing work
- [x] Add a "pre-commit" command target that runs `pre-commit` as a new commit and pushes.
- [x] Test `black` and `pre-commit` in a [PR](https://github.com/blink1073/jupyter_server/pull/6)
- [x] Add docstrings
- [x] Add documentation 
- [x] Make a `run` convenience function that prints the command
- [x] Make `keen` optional so it isn't needed in non-prod apps (costs $300/mo on team account)
- [x] Add contributor guide
- [x] Add pre-commit config with flake8
- [x] Add GitHub Actions testing (will require a B64KEY secret in this repo) - passing [test](https://github.com/blink1073/MeeseeksDev/actions/runs/2027856035)

This is an on-demand alternative to the more disruptive "auto fixing pull requests" from https://pre-commit.ci/

### CODE REVIEW

**Comment by blink1073** [comment]
cc @choldgraf @consideRatio

**Review by Carreau — APPROVED** [review]
Let me know if you have access to heroku to debug if there are issues.

**Comment by blink1073** [comment]
On further thought, this won't work because if the hook changes anything it is considered a failure.  Will need to do some more refactoring.

**Comment by blink1073** [comment]
@Carreau I don't think I have access to that heroku app, my account is under steven.silvester at gmail.com.

**Comment by blink1073** [comment]
Oh I see what you mean, I can deploy this myself.

**Comment by consideRatio** [comment]
Hi @blink1073!
Let me know if you want review or input with something specific @blink1073!

Note that I've not worked on this bot and hasn't used it besides learning that it can be used for backporting PRs by Min. Quickly glancing at the code I didn't see docstrings which otherwise could help me review something unknown by just knowing that the docstring declares the objective of a function.

I guess a technical review point could be that it would be good if you add docstrings to any function you add or re-purpose to help newcomers! :)

**Comment by blink1073** [comment]
Converting to draft while I test in https://github.com/blink1073/MeeseeksDev/pull/1.  I'm putting this aside for the weekend.

**Comment by Carreau** [comment]
To deploy you can just merge this. 
The heroku access is mostly for `heroku logs --tail` to help debugging if it fails somewhere.

**Comment by Carreau** [comment]
(and feel free to merge-try-revert to test if you need.)

**Comment by blink1073** [comment]
@Carreau I've finished.  I ended up adding flake8 and GitHub Actions support.

**Comment by blink1073** [comment]
@consideRatio thanks for the feedback!  I was pinging you and Chris as potential users of the new feature, no review required.

**Comment by Carreau** [comment]
Ok, let's just merge and see if things break. <3

**Comment by Carreau** [comment]
Sorry, I thought you were.

**Comment by blink1073** [comment]
> I also invited you to the org in case you need even more permissions.

Cheers

**Pull request merged**
