### PR TITLE
Update allowlist

### PR DESCRIPTION
**Pull request by blink1073**
Add Jupyter orgs and @kevin-bates to allowlist and rename to avoid insensitive terminology.

### CODE REVIEW

**Review by kevin-bates — APPROVED** [review]
Thanks @blink1073 - these changes look good!

**Comment by Carreau** [comment]
I think we should just make the bot public, and remove the allow_list altogether

**Comment by blink1073** [comment]
My concern there is that we're using the free tier, and if we upgrade then the Keen plugin costs $300/mo

**Comment by Carreau** [comment]
> My concern there is that we're using the free tier, and if we upgrade then the Keen plugin costs $300/mo

Fair enough.

**Pull request merged**
